baseURL = "/"
title = "启付盒"
theme = "hugo-theme-stack"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
paginate = 8
enableRobotsTXT = true

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[outputs]
    home = ["HTML", "RSS"]
    section = ["HTML", "RSS"]
    page = ["HTML"]

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[markup.goldmark.renderer]
    unsafe = true

[imaging]
    quality = 80
    resampleFilter = "Box"
