# 主题配置
mainSections = ["post"]
description = "奇伏禾的个人博客"
[dateFormat]
    published = "2006-01-02"
    lastUpdated = "2006-01-02"

# 主页信息
siteTitle = "奇伏禾"
siteSubtitle = "记录成长，分享知识"

# 侧边栏头像
avatar = "/img/avatar.png"

# 页脚信息
since = 2025

# 社交链接
[[social]]
    name = "GitHub"
    link = "https://github.com/qifuhe"

[[social]]
    name = "Email"
    link = "mailto:i@qifuhe.com"

# 颜色主题
colorScheme = "auto"
sidebarCompact = false
